-- PostgreSQL initialization script
-- Creates tables for fraud detection system

-- Drop tables if they exist (for clean setup)
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS merchant_daily_metrics CASCADE;

-- Merchant Daily Metrics Table
CREATE TABLE merchant_daily_metrics (
    dt DATE NOT NULL,
    merchant_id VARCHAR(50) NOT NULL,
    tx_count INTEGER NOT NULL,
    sum_amount NUMERIC(15, 2) NOT NULL,
    avg_amount NUMERIC(15, 2) NOT NULL,
    max_amount NUMERIC(15, 2) NOT NULL,
    unique_countries INTEGER NOT NULL,
    unique_devices INTEGER NOT NULL,
    decline_rate NUMERIC(6, 4) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (dt, merchant_id)
);

-- Create indexes for common queries
CREATE INDEX idx_merchant_metrics_dt ON merchant_daily_metrics(dt);
CREATE INDEX idx_merchant_metrics_merchant ON merchant_daily_metrics(merchant_id);
CREATE INDEX idx_merchant_metrics_tx_count ON merchant_daily_metrics(tx_count DESC);
CREATE INDEX idx_merchant_metrics_sum_amount ON merchant_daily_metrics(sum_amount DESC);
CREATE INDEX idx_merchant_metrics_max_amount ON merchant_daily_metrics(max_amount DESC);

-- Alerts Table
CREATE TABLE alerts (
    alert_id SERIAL PRIMARY KEY,
    dt DATE NOT NULL,
    merchant_id VARCHAR(50),
    customer_id VARCHAR(50),
    rule_code VARCHAR(50) NOT NULL,
    severity INTEGER NOT NULL,
    details JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for common queries
CREATE INDEX idx_alerts_dt ON alerts(dt);
CREATE INDEX idx_alerts_merchant ON alerts(merchant_id);
CREATE INDEX idx_alerts_customer ON alerts(customer_id);
CREATE INDEX idx_alerts_severity ON alerts(severity DESC);
CREATE INDEX idx_alerts_rule ON alerts(rule_code);
CREATE INDEX idx_alerts_created ON alerts(created_at DESC);

-- Create a view for alert summaries
CREATE OR REPLACE VIEW alert_summary AS
SELECT 
    dt,
    rule_code,
    severity,
    COUNT(*) as alert_count,
    COUNT(DISTINCT merchant_id) as affected_merchants,
    COUNT(DISTINCT customer_id) as affected_customers
FROM alerts
GROUP BY dt, rule_code, severity
ORDER BY dt DESC, severity DESC;

-- Grant permissions
GRANT ALL PRIVILEGES ON TABLE merchant_daily_metrics TO fraud_user;
GRANT ALL PRIVILEGES ON TABLE alerts TO fraud_user;
GRANT USAGE, SELECT ON SEQUENCE alerts_alert_id_seq TO fraud_user;
GRANT SELECT ON alert_summary TO fraud_user;

-- Insert some comments for documentation
COMMENT ON TABLE merchant_daily_metrics IS 'Daily aggregated metrics per merchant for fraud detection';
COMMENT ON TABLE alerts IS 'Fraud risk alerts generated by rule-based system';
COMMENT ON COLUMN alerts.severity IS 'Alert severity: 1=Low, 2=Medium, 3=High';
COMMENT ON COLUMN alerts.details IS 'JSON details about the alert trigger';
